name: ISI Burger CI/CD

on:
  push:
    branches: [ momy_diop_burger ]
  pull_request:
    branches: [ momy_diop_burger ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull du code depuis GitHub
        uses: actions/checkout@v4

      - name: Installation de PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, bcmath, gd, zip

      - name: Copier le fichier .env
        run: cp .env.example .env

      - name: Installation des dépendances Laravel
        run: composer install --no-dev --optimize-autoloader

      - name: Générer la clé Laravel
        run: php artisan key:generate

      - name: Installation Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build des assets
        run: |
          npm install
          npm run build

      - name: Création image Docker
        run: docker build -t isi-burger:latest .

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image sur Docker Hub
        run: |
          docker tag isi-burger:latest ${{ secrets.DOCKER_USERNAME }}/isi-burger:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/isi-burger:latest
